### ISSUE TITLE
gmail: this message may not have been sent by

### ISSUE THREAD

**Issue by bennn** [bennn/racket-mutt#1]
My `~/.muttrc` is sending mail from a gmail address to another gmail address.
The messages arrive, but gmail puts a warning in the message: "May not have been sent by <me>".

Should be able to fix this by changing the `.muttrc` to use gmail's `imap` or `smtp` interface, but I haven't figured out how.

**Comment by bennn** [comment]
https://www.linux.com/blog/setup-mutt-gmail-centos-and-ubuntu

**Comment by bennn** [comment]
From Leif:

"Apparently its an os x bug...adding the following line to your .muttrc works:

set smtp_authenticators = 'gssapi:login'"

**Comment by bennn** [comment]
ugh, I can't get anything to send though gmail.

Even after enabling POP / IMAP

**Comment by pirj** [comment]
```
set smtp_url=smtps://$imap_user:$imap_pass@smtp.gmail.com
```
This worked for me to get rid of the same issue (bare mutt).

**Comment by bennn** [comment]
Thank you!

- First I tried the url you suggested, with username & password, but saw `Invalid SMTP URL` (maybe because of special characters in my password)
- Next I removed `:$imap_pass` and `set smtp_pass` in my `.muttrc`; with that I was able to see my gmail inbox using plain `mutt`
- After accepting the certificate from gmail in `mutt`, I was able to send with this library

- - -

Outline of my `.muttrc`:

```
set realname = "<name>"
set from = "<username@gmail.com>"
set use_from = yes
set envelope_from = yes

set imap_user = $from
set imap_pass = "<password>"
set smtp_url = "smtps://$imap_user@smtp.gmail.com:465/"
set smtp_pass = $imap_pass
set folder = "imaps://imap.gmail.com:993"
set spoolfile = "+INBOX"
set ssl_force_tls = yes
set smtp_authenticators = 'gssapi:login'
set header_cache = "~/.mutt/cache/"
```

**Comment by bennn** [comment]
edd94e064993f8e079fd445a6742c884fcbfcbc6

**Comment by cirosantilli** [comment]
I would also recommend looking at the recommendations on the official Mutt wiki: https://gitlab.com/muttmua/mutt/wikis/UseCases/Gmail as they worked for me.
