### ISSUE TITLE
`mutt` fails with attachment provided as path

### ISSUE THREAD

**Issue by jasonhemann** [bennn/racket-mutt#25]
I see the following error when trying to send mail w/an attachment.

```
 (mutt "" #:to "test@example.com" #:attachment (build-path "./test"))
; string-join: contract violation
;   expected: (listof string?)
;   given: '(#<path:./test>)
; Context (errortrace):
;    create-scores-hash.rkt:64:0: (mutt "" #:to "test@example.com" #:attachment (build-path "./test"))
```

I believe mutt is expecting the attachments as path strings. But by the time we get to formatting, we seem to be expecting only strings, since we're doing a [string-join](https://github.com/bennn/racket-mutt/blob/8f85ee8f1d4c4c14077b9396e51647ef6fc53f00/private/main.rkt#L156). Maybe some special casing around [here](https://github.com/bennn/racket-mutt/blob/master/private/main.rkt#L129)?

**Comment by bennn** [comment]
Pushed a fix. Thanks for the report!
